# Site settings
title: Lyuha's Log
baseurl: "/blog"
url: "http://blog.lyuha.me" # the base hostname & protocol for your site
github_username: lyuha
timezone: Asia/Seoul

# Build settings
markdown: kramdown
highlighter: rouge
